WITH TABLE_A AS (
SELECT 'A' AS A_ID, 1 AS A_VALUE FROM DUAL
UNION
SELECT 'B' AS A_ID, 2 AS A_VALUE FROM DUAL
UNION
SELECT 'C' AS A_ID, 3 AS A_VALUE FROM DUAL
),
TABLE_B AS (
SELECT 'B' AS B_ID, 2 AS B_VALUE FROM DUAL
UNION
SELECT 'C' AS B_ID, 3 AS B_VALUE FROM DUAL
UNION
SELECT 'D' AS B_ID, NULL AS B_VALUE FROM DUAL
)
SELECT SUM(TBB.B_VALUE)
FROM TABLE_A TBA
     ,TABLE_B TBB
WHERE TBA.A_ID <> TBB.B_ID;