WITH T1 AS (
SELECT 'A' AS ID, '유재석' AS NAME FROM DUAL
UNION
SELECT 'B' AS ID, '박명수' AS NAME FROM DUAL
UNION
SELECT 'C' AS ID, '노홍철' AS NAME FROM DUAL
),
T2 AS (
SELECT 'B' AS ID, 'SM5' AS CAR FROM DUAL
UNION
SELECT 'C' AS ID, 'CAMARO' AS CAR FROM DUAL
)
SELECT T1.ID, T1.NAME, T2.CAR
FROM T1 LEFT OUTER JOIN T2
ON T1.ID = T2.ID
ORDER BY T1.ID;


WITH T1 AS (
SELECT 'A' AS ID, '유재석' AS NAME FROM DUAL
UNION
SELECT 'B' AS ID, '박명수' AS NAME FROM DUAL
UNION
SELECT 'C' AS ID, '노홍철' AS NAME FROM DUAL
),
T2 AS (
SELECT 'B' AS ID, 'SM5' AS CAR FROM DUAL
UNION
SELECT 'C' AS ID, 'CAMARO' AS CAR FROM DUAL
)
SELECT T1.ID, T1.NAME, T2.CAR
FROM T1 FULL OUTER JOIN T2
ON T1.ID = T2.ID
ORDER BY T1.ID;


WITH T1 AS (
SELECT 'A' AS ID, '유재석' AS NAME FROM DUAL
UNION
SELECT 'B' AS ID, '박명수' AS NAME FROM DUAL
UNION
SELECT 'C' AS ID, '노홍철' AS NAME FROM DUAL
),
T2 AS (
SELECT 'B' AS ID, 'SM5' AS CAR FROM DUAL
UNION
SELECT 'C' AS ID, 'CAMARO' AS CAR FROM DUAL
)
SELECT T1.ID, T1.NAME, T2.CAR
FROM T1, T2
WHERE T1.ID = T2.ID(+);