WITH TIME_CALC AS(
SELECT TO_DATE('2016/02/01','YYYY/MM/DD') AS CALC_DATE
FROM DUAL
UNION
SELECT TO_DATE('2016/01/01','YYYY/MM/DD') AS CALC_DATE
FROM DUAL
UNION
SELECT TO_DATE('2015/08/01','YYYY/MM/DD') AS CALC_DATE
FROM DUAL
)
SELECT *
FROM TIME_CALC;



WITH TIME_CALC AS(
SELECT TO_DATE('2016/02/01','YYYY/MM/DD') AS CALC_DATE
FROM DUAL
UNION
SELECT TO_DATE('2016/01/01','YYYY/MM/DD') AS CALC_DATE
FROM DUAL
UNION
SELECT TO_DATE('2015/08/01','YYYY/MM/DD') AS CALC_DATE
FROM DUAL
)
SELECT CALC_DATE - 1 * 31 AS CALC_DATE
FROM TIME_CALC;



WITH TIME_CALC AS(
SELECT TO_DATE('2016/02/01','YYYY/MM/DD') AS CALC_DATE
FROM DUAL
UNION
SELECT TO_DATE('2016/01/01','YYYY/MM/DD') AS CALC_DATE
FROM DUAL
UNION
SELECT TO_DATE('2015/08/01','YYYY/MM/DD') AS CALC_DATE
FROM DUAL
)
SELECT ADD_MONTHS(CALC_DATE,-1) AS CALC_DATE
FROM TIME_CALC;